# Generated by Django 4.2.30 on 2026-08-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='type',
            field=models.CharField(choices=[('CHARGE', '예치금 충전'), ('WITHDRAW', '예치금 출금'), ('INVEST', '투자 실행'), ('INVEST_REFUND', '투자 환불'), ('DISTRIBUTION', '상환 분배금 수령'), ('REPAY', '차주 상환 납부'), ('PLATFORM_FEE', '플랫폼 수수료')], max_length=20),
        ),
    ]
