# Generated by Django 4.2.30 on 2026-07-05 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purpose', models.CharField(max_length=200)),
                ('term_months', models.PositiveSmallIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', '심사중'), ('APPROVED', '승인'), ('REJECTED', '거절')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('investor_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('funded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('term_months', models.PositiveSmallIntegerField()),
                ('funding_deadline', models.DateField()),
                ('status', models.CharField(choices=[('FUNDRAISING', '모집중'), ('ACTIVE', '실행중'), ('OVERDUE_1', '연체1'), ('OVERDUE_2', '연체2'), ('DEFAULT', '부실'), ('WRITTEN_OFF', '상각'), ('COMPLETED', '완료')], default='FUNDRAISING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
