# Generated by Django 4.2.30 on 2026-07-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='interest_rate',
        ),
    ]
