# Generated by Django 4.2.30 on 2026-08-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loanapplication_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('FUNDRAISING', '모집중'), ('ACTIVE', '실행중'), ('OVERDUE_1', '연체1'), ('OVERDUE_2', '연체2'), ('DEFAULT', '부실'), ('WRITTEN_OFF', '상각'), ('COMPLETED', '완료'), ('CANCELLED', '모집취소')], default='FUNDRAISING', max_length=12),
        ),
    ]
