# Generated by Django 4.2.30 on 2026-07-08 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0002_remove_loanapplication_interest_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', '미납'), ('PAID', '납부완료')], default='PENDING', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_schedules', to='loans.loan')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='repaymentschedule',
            constraint=models.UniqueConstraint(fields=('loan', 'installment_number'), name='unique_loan_installment_number'),
        ),
    ]
