# Generated by Django 4.2.30 on 2026-09-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayments', '0002_repayment_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='distributed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
